# Generated by Django 5.2.1 on 2025-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintheme',
            name='css_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='js_url',
            field=models.CharField(max_length=255),
        ),
    ]
